---
- name: Add apt FRR apt key 
  apt_key:
    url: https://deb.frrouting.org/frr/keys.asc 
    state: present

- apt_repository:
    repo: deb https://deb.frrouting.org/frr bionic frr-stable 
    state: present

- name: Install Frrouting
  apt: 
    name: ['frr','frr-pythontools']
    state: present

- name: Sysctl ipv4 forward
  sysctl:
    name: net.ipv4.conf.all.forwarding 
    value: 1
    state: present
    reload: yes

- name: Sysctl ipv4 forward
  sysctl:
    name: net.ipv4.conf.default.forwarding 
    value: 1
    state: present
    reload: yes

- name: Sysctl ipv6 forward
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    state: present
    reload: yes 

- name: Sysctl ipv6 forward
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: 1
    state: present
    reload: yes 

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking 

- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Reboot system
  reboot:
    reboot_timeout: 1200
    test_command: mount  
...
