---
- name: Ping to learn prefixes
  command: screen -dm ip vrf exec "{{ item.app }}" ping 192.168."{{ item.prefix }}"."{{ item.destination }}" -c 120
  loop:
    - { app: 'app1', prefix: '12', destination: '11'}
    - { app: 'app1', prefix: '12', destination: '12'}
    - { app: 'app1', prefix: '12', destination: '13'}
    - { app: 'app1', prefix: '12', destination: '14'}
    - { app: 'app1', prefix: '12', destination: '15'}
    - { app: 'app1', prefix: '12', destination: '16'}
    - { app: 'app1', prefix: '12', destination: '17'}
    - { app: 'app1', prefix: '12', destination: '18'}
    - { app: 'app1', prefix: '12', destination: '19'}
    - { app: 'app1', prefix: '12', destination: '20'}
    - { app: 'app2', prefix: '11', destination: '11'}
    - { app: 'app2', prefix: '11', destination: '12'}
    - { app: 'app2', prefix: '11', destination: '13'}
    - { app: 'app2', prefix: '11', destination: '14'}
    - { app: 'app2', prefix: '11', destination: '15'}
    - { app: 'app2', prefix: '11', destination: '16'}
    - { app: 'app2', prefix: '11', destination: '17'}
    - { app: 'app2', prefix: '11', destination: '18'}
    - { app: 'app2', prefix: '11', destination: '19'}
    - { app: 'app2', prefix: '11', destination: '20'}
    - { app: 'app3', prefix: '14', destination: '11'}
    - { app: 'app3', prefix: '14', destination: '12'}
    - { app: 'app3', prefix: '14', destination: '13'}
    - { app: 'app3', prefix: '14', destination: '14'}
    - { app: 'app3', prefix: '14', destination: '15'}
    - { app: 'app3', prefix: '14', destination: '16'}
    - { app: 'app3', prefix: '14', destination: '17'}
    - { app: 'app3', prefix: '14', destination: '18'}
    - { app: 'app3', prefix: '14', destination: '19'}
    - { app: 'app3', prefix: '14', destination: '20'}
    - { app: 'app4', prefix: '13', destination: '11'}
    - { app: 'app4', prefix: '13', destination: '12'}
    - { app: 'app4', prefix: '13', destination: '13'}
    - { app: 'app4', prefix: '13', destination: '14'}
    - { app: 'app4', prefix: '13', destination: '15'}
    - { app: 'app4', prefix: '13', destination: '16'}
    - { app: 'app4', prefix: '13', destination: '17'}
    - { app: 'app4', prefix: '13', destination: '18'}
    - { app: 'app4', prefix: '13', destination: '19'}
    - { app: 'app4', prefix: '13', destination: '20'}
    - { app: 'app5', prefix: '16', destination: '11'}
    - { app: 'app5', prefix: '16', destination: '12'}
    - { app: 'app5', prefix: '16', destination: '13'}
    - { app: 'app5', prefix: '16', destination: '14'}
    - { app: 'app5', prefix: '16', destination: '15'}
    - { app: 'app5', prefix: '16', destination: '16'}
    - { app: 'app5', prefix: '16', destination: '17'}
    - { app: 'app5', prefix: '16', destination: '18'}
    - { app: 'app5', prefix: '16', destination: '19'}
    - { app: 'app5', prefix: '16', destination: '20'}
    - { app: 'app6', prefix: '15', destination: '11'}
    - { app: 'app6', prefix: '15', destination: '12'}
    - { app: 'app6', prefix: '15', destination: '13'}
    - { app: 'app6', prefix: '15', destination: '14'}
    - { app: 'app6', prefix: '15', destination: '15'}
    - { app: 'app6', prefix: '15', destination: '16'}
    - { app: 'app6', prefix: '15', destination: '17'}
    - { app: 'app6', prefix: '15', destination: '18'}
    - { app: 'app6', prefix: '15', destination: '19'}
    - { app: 'app6', prefix: '15', destination: '20'}

- name: Ping6 to learn prefixes
  command: screen -dm ip vrf exec "{{ item.app }}" ping6 fc00:"{{ item.prefix }}"::"{{ item.destination }}" -c 120
  loop:
    - { app: 'app1', prefix: '12', destination: '11'}
    - { app: 'app1', prefix: '12', destination: '12'}
    - { app: 'app1', prefix: '12', destination: '13'}
    - { app: 'app1', prefix: '12', destination: '14'}
    - { app: 'app1', prefix: '12', destination: '15'}
    - { app: 'app1', prefix: '12', destination: '16'}
    - { app: 'app1', prefix: '12', destination: '17'}
    - { app: 'app1', prefix: '12', destination: '18'}
    - { app: 'app1', prefix: '12', destination: '19'}
    - { app: 'app1', prefix: '12', destination: '20'}
    - { app: 'app2', prefix: '11', destination: '11'}
    - { app: 'app2', prefix: '11', destination: '12'}
    - { app: 'app2', prefix: '11', destination: '13'}
    - { app: 'app2', prefix: '11', destination: '14'}
    - { app: 'app2', prefix: '11', destination: '15'}
    - { app: 'app2', prefix: '11', destination: '16'}
    - { app: 'app2', prefix: '11', destination: '17'}
    - { app: 'app2', prefix: '11', destination: '18'}
    - { app: 'app2', prefix: '11', destination: '19'}
    - { app: 'app2', prefix: '11', destination: '20'}
    - { app: 'app3', prefix: '14', destination: '11'}
    - { app: 'app3', prefix: '14', destination: '12'}
    - { app: 'app3', prefix: '14', destination: '13'}
    - { app: 'app3', prefix: '14', destination: '14'}
    - { app: 'app3', prefix: '14', destination: '15'}
    - { app: 'app3', prefix: '14', destination: '16'}
    - { app: 'app3', prefix: '14', destination: '17'}
    - { app: 'app3', prefix: '14', destination: '18'}
    - { app: 'app3', prefix: '14', destination: '19'}
    - { app: 'app3', prefix: '14', destination: '20'}
    - { app: 'app4', prefix: '13', destination: '11'}
    - { app: 'app4', prefix: '13', destination: '12'}
    - { app: 'app4', prefix: '13', destination: '13'}
    - { app: 'app4', prefix: '13', destination: '14'}
    - { app: 'app4', prefix: '13', destination: '15'}
    - { app: 'app4', prefix: '13', destination: '16'}
    - { app: 'app4', prefix: '13', destination: '17'}
    - { app: 'app4', prefix: '13', destination: '18'}
    - { app: 'app4', prefix: '13', destination: '19'}
    - { app: 'app4', prefix: '13', destination: '20'}
    - { app: 'app5', prefix: '16', destination: '11'}
    - { app: 'app5', prefix: '16', destination: '12'}
    - { app: 'app5', prefix: '16', destination: '13'}
    - { app: 'app5', prefix: '16', destination: '14'}
    - { app: 'app5', prefix: '16', destination: '15'}
    - { app: 'app5', prefix: '16', destination: '16'}
    - { app: 'app5', prefix: '16', destination: '17'}
    - { app: 'app5', prefix: '16', destination: '18'}
    - { app: 'app5', prefix: '16', destination: '19'}
    - { app: 'app5', prefix: '16', destination: '20'}
    - { app: 'app6', prefix: '15', destination: '11'}
    - { app: 'app6', prefix: '15', destination: '12'}
    - { app: 'app6', prefix: '15', destination: '13'}
    - { app: 'app6', prefix: '15', destination: '14'}
    - { app: 'app6', prefix: '15', destination: '15'}
    - { app: 'app6', prefix: '15', destination: '16'}
    - { app: 'app6', prefix: '15', destination: '17'}
    - { app: 'app6', prefix: '15', destination: '18'}
    - { app: 'app6', prefix: '15', destination: '19'}
    - { app: 'app6', prefix: '15', destination: '20'}
...
